---
title: "Exercise1-2 XuechunWang"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE)
```

trim level 350
========================================================

```{r, echo=FALSE}
library(mosaic)
library(readr)
sclass <- read_csv("sclass.csv")
sclass350 = subset(sclass, trim== '350')
sclass65AMG = subset(sclass, trim== '65 AMG')

library(tidyverse)
library(FNN)
library(foreach)


ggplot(data = sclass350) + 
  geom_point(mapping = aes(x = mileage, y = price), color='darkgrey')
```

trim level 350: out of sample RMSE versus K
========================================================

```{r, echo=FALSE}
N1 = nrow(sclass350)
N_train1 = floor(0.8*N1)
N_test1 = N1 - N_train1

train_ind1 = sample.int(N1, N_train1, replace=FALSE)

D_train1 = sclass350[train_ind1,]
D_test1 = sclass350[-train_ind1,]

D_test1 = arrange(D_test1, mileage)

X_train1 = select(D_train1, mileage)
y_train1 = select(D_train1, price)
X_test1 = select(D_test1, mileage)
y_test1 = select(D_test1, price)

rmse = function(y, ypred) {
  sqrt(mean(data.matrix((y-ypred)^2)))
}

k_grid1_1 = unique(round(exp(seq(log(330), log(3), length=100))))
rmse_grid_out1 = foreach(k = k_grid1_1, .combine='c') %do% {
  knn_model1_1 = knn.reg(X_train1, X_test1, as.data.frame(y_train1), k = k)
  rmse(y_test1, knn_model1_1$pred)
}

rmse_grid_out1 = data.frame(K = k_grid1_1, RMSE = rmse_grid_out1)

p_out = ggplot(data=rmse_grid_out1) + 
  geom_path(aes(x=K, y=RMSE, color='testset'), size=1.5)
p_out

ind_best = which.min(rmse_grid_out1$RMSE)
k_best = k_grid1_1[ind_best]
k_best
```

trim level 350: RMSE versus K
========================================================

```{r, echo=FALSE}
k_grid1_2 = unique(round(exp(seq(log(330), log(3), length=100))))
rmse_grid_in1 = foreach(k = k_grid1_2, .combine='c') %do% {
  knn_model1_2 = knn.reg(X_train1, X_train1, as.data.frame(y_train1), k = k)
  rmse(y_train1, knn_model1_2$pred)
}

rmse_grid_in1 = data.frame(K = k_grid1_2, RMSE = rmse_grid_in1)
ggplot(data=rmse_grid_in1) + 
  geom_path(aes(x=K, y=RMSE, color='testset'), size=1.5) 
```

trim level 350: RMSE(2 types) versus K
========================================================

```{r,echo=FALSE}
p_out + geom_path(data=rmse_grid_in1, aes(x=K, y=RMSE, color='trainset'),size=1.5) + 
  scale_colour_manual(name="RMSE",
                      values=c(testset="black", trainset="grey")) + 
  geom_vline(xintercept=k_best, color='darkgreen', size=1.5)
```

trim level 350: K-nearest neighbors at the optimal K
========================================================

```{r,echo=FALSE}
knn_model_optimal = knn.reg(X_train1, X_test1, as.data.frame(y_train1), k = k_best)
d_test1 = data.frame(X_test1, ypred = knn_model_optimal$pred)
p_base1 = ggplot(data = sclass350) + 
  geom_point(mapping = aes(x =mileage , y = price), color='darkgrey') 

p_base1 + geom_path(data=d_test1, mapping = aes(x = mileage, y = ypred), color='red', size=1.5)
```

trim level 65AMG
========================================================

```{r,echo=FALSE}
ggplot(data = sclass65AMG) + 
  geom_point(mapping = aes(x = mileage, y = price), color='darkgrey') 
```

trim level 65AMG: out of sample RMSE versus K
========================================================

```{r,echo=FALSE}
N2 = nrow(sclass65AMG)
N_train2 = floor(0.8*N2)
N_test2 = N2 - N_train2

train_ind2 = sample.int(N2, N_train2, replace=FALSE)

D_train2 = sclass65AMG[train_ind2,]
D_test2 = sclass65AMG[-train_ind2,]

D_test2 = arrange(D_test2, mileage)

X_train2 = select(D_train2, mileage)
y_train2 = select(D_train2, price)
X_test2 = select(D_test2, mileage)
y_test2 = select(D_test2, price)

rmse = function(y, ypred) {
  sqrt(mean(data.matrix((y-ypred)^2)))
}

k_grid2_1 = unique(round(exp(seq(log(230), log(3), length=100))))
rmse_grid_out2 = foreach(k = k_grid2_1, .combine='c') %do% {
  knn_model2_1 = knn.reg(X_train2, X_test2,as.data.frame( y_train2), k = k)
  rmse(y_test2, knn_model2_1$pred)
}

rmse_grid_out2 = data.frame(K = k_grid2_1, RMSE = rmse_grid_out2)

p_out = ggplot(data=rmse_grid_out2) + 
  geom_path(aes(x=K, y=RMSE, color='testset'), size=1.5)
p_out

ind_best = which.min(rmse_grid_out2$RMSE)
k_best = k_grid2_1[ind_best]
k_best
```

trim level 65AMG: RMSE versus K
========================================================

```{r,echo=FALSE}
k_grid2_2 = unique(round(exp(seq(log(230), log(3), length=100))))
rmse_grid_in2 = foreach(k = k_grid2_2, .combine='c') %do% {
  knn_model2_2 = knn.reg(X_train2, X_train2, as.data.frame(y_train2), k = k)
  rmse(y_train2, knn_model2_2$pred)
}

rmse_grid_in2 = data.frame(K = k_grid2_2, RMSE = rmse_grid_in2)
ggplot(data=rmse_grid_in2) + 
  geom_path(aes(x=K, y=RMSE, color='testset'), size=1.5) 
```

trim level 65AMG: RMSE(2 types) versus K
========================================================

```{r,echo=FALSE}
p_out + geom_path(data=rmse_grid_in2, aes(x=K, y=RMSE, color='trainset'),size=1.5) + 
  scale_colour_manual(name="RMSE",
                      values=c(testset="black", trainset="grey")) + 
  geom_vline(xintercept=k_best, color='darkgreen', size=1.5)
```